### ISSUE TITLE
Add drops (optional)

### ISSUE THREAD

**Issue by iarspider** [creadri/LazyRoad#3]
Please add an option to drop all (or only "useful", like ores/coal - from a custom list) blocks that gets destroyed/replaced when building a road/tunnel

**Comment by creadri** [comment]
ATM, the programming structure isn't designed to allow such modification in an easy and efficient way. Thus, I'll need to rewrite some code to include it as an optional feature. It's not really up to schedule but I'll thing about it. Thanks for the feature idea.

**Comment by wolfwoodbrbu** [comment]
The only problem I have with this is that when you undo you'd keep the ore gained. If I do add this I will make it not input the ore into the undo system the ore if this option is set, it would be a lazy miner feature.

**Comment by iarspider** [comment]
Lazy miner? Why not? :)
On Mar 31, 2012 6:25 PM, "wolfwoodbrbu" <
reply@reply.github.com>
wrote:

**Comment by wolfwoodbrbu** [comment]
I actually think it wouldn't be as hard as creadri thought it would. I'd hook it into the undo system because that already logs every block that gets replaced and putting a block list in the config wouldn't be hard at all. 

It'll probably be inserted into you inventory not dropped as an item.
It'll warn when you only have 1 empty slot left in your inventory.

I don't know when I'll get to this but I like the idea now.
I'll make this a milestone so I don't forget it.

**Comment by wolfwoodbrbu** [comment]
It took me better part of 2 days of coding but I finally have a version for release with the LazyMiner Feature.

http://dev.bukkit.org/server-mods/lazyroad/files/12-lazy-road-v0-8-0/

**Comment by iarspider** [comment]
Let the LazyMining begin  ;) Thanks!

**Comment by wolfwoodbrbu** [comment]
No problem. It was good experience. It was the first time I worked with serializing a class so I could save the data to disc. Now that I know how to do that I'll have a easier time when I rewrite the rest of the plugin to be better.
