### ISSUE TITLE
No roads come up .

### ISSUE THREAD

**Issue by MrRandom** [creadri/LazyRoad#4]
Hi !
I run a 24/7 where i use clanforge as a command center and stuff.. I downloaded the file, uploaded it to the staff who run clanforge and they told me that they put it in the plugins folder

I added lazy road to my plugins and I went to my server and typed :/road the only thing that come up is 
Roads ------------- Pillar
Page 0 of 0

I opened up the .jar file and the roads where there.. im the admin so my name was on the op list, i even added the permission node..

I went on to install permissionEx and same problem

and the only file i got when i installed Lazyroad was the message file. with the error etc..

Im on minecraft beta 1.8.1

can you help? the people on my server wants this plugin.

**Comment by creadri** [comment]
If the plugin does not detect the "roads" and "pillars" folders, it copies and unzip it. If the folder does exists it does nothing. So, try delete the lazyroad folder and restart your server. This should fix your problem. You also can manually push the roads and pillars.

It's perhaps a unix folder permission problem, since to unzip the files I have to rely on a temporary location. You may not have access to that, a little odd though.

You should have some ftp access or something like that, just push manually the road files and reload your server, this should do the trick.

And it's not a bukkit permission problem, that's sure.

**Comment by wolfwoodbrbu** [comment]
Closing old fixed issues.
